on:
  push:
    branches:
      [ production ]

jobs:
  Push_to_Docker_Hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest

  Deploy_to_the_Citadel:
    name: Deploy to the Citadel
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: "Execute the deployment script"
        run: chmod +x scripts/deploy.sh && ./scripts/deploy.sh