run-name: ${{ inputs.message }}

on:
  push:
    branches:
      [ production, development ]
  workflow_dispatch:
    inputs:
      message:
        description: 'The message of the Workflow Run'
        required: true
        type: string

jobs:
  Push_to_Docker_Hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/production' && 'Production' || 'Test' }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest

  Deploy_to_the_Citadel:
    name: Deploy to the Citadel
    runs-on: ubuntu-latest
    environment: Production
    needs: Push_to_Docker_Hub
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Execute the deployment script
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
          CONTAINER_PORT: ${{ vars.CONTAINER_PORT }}
          HOST_PORT: ${{ vars.HOST_PORT }}
          CITADEL_SSH_PRIVATE_KEY: ${{ github.ref == 'refs/heads/production' && secrets.CITADEL_SSH_PRIVATE_KEY || secrets.CITADEL_TEST_SSH_PRIVATE_KEY }}
          CITADEL_USERNAME: ${{ vars.CITADEL_USERNAME }}
          CITADEL_HOST_NAME: ${{ github.ref == 'refs/heads/production' && vars.CITADEL_HOST_NAME || vars.CITADEL_TEST_HOST_NAME }}
          ENVIRONMENT: ${{ github.ref == 'refs/heads/production' && 'Production' || 'Test' }}
        run: chmod +x scripts/deploy.sh && ./scripts/deploy.sh