name: Push to Docker Hub and Deploy to Azure Container

on:
  push:
    branches:
      [ production ]

permissions:
  id-token: write

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry and deploy to Azure container
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: docker.io
          registryUsername: ${{ vars.DOCKERHUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          containerAppName: ${{ vars.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          imageToBuild: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest
          environmentVariables: ENVIRONMENT=${{ vars.ENVIRONMENT }} CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}

      - name: Restart Revision
        shell: bash
        run: |
          export REVISION_NAME=$(az containerapp revision list --name ${{ vars.AZURE_CONTAINER_APP_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} --query "[0].name")
          az containerapp revision restart --revision "${REVISION_NAME//\"/}" --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }}